In [1]:
import numpy as np
from sklearn import preprocessing

In [7]:
input_data = np.array([[3, -1.5, 3, -6.4], [0,3,-1.3,4.1], [1,2.3,-2.9, -4.3]])

In [8]:
data_standardized = preprocessing.scale(input_data)

In [9]:
print('\nMean = ', data_standardized.mean(axis=0))
print('Std deviation = ', data_standardized.std(axis=0))


Mean =  [ 5.55111512e-17 -3.70074342e-17  0.00000000e+00 -1.85037171e-17]
Std deviation =  [1. 1. 1. 1.]


In [11]:
data_scaler = preprocessing.MinMaxScaler(feature_range=(0,1))
data_scaled = data_scaler.fit_transform(input_data)
print('\nMin max scaled data = ', data_scaled )


Min max scaled data =  [[1.         0.         1.         0.        ]
 [0.         1.         0.27118644 1.        ]
 [0.33333333 0.84444444 0.         0.2       ]]


In [12]:
data_normalized = preprocessing.normalize(input_data, norm='l1')
print('\nL1 normalized data = ', data_normalized)


L1 normalized data =  [[ 0.21582734 -0.10791367  0.21582734 -0.46043165]
 [ 0.          0.35714286 -0.1547619   0.48809524]
 [ 0.0952381   0.21904762 -0.27619048 -0.40952381]]


In [14]:
data_binarized = preprocessing.Binarizer(threshold=1.4).transform(input_data)
print('\nBinarized data =', data_binarized)


Binarized data = [[1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [0. 1. 0. 0.]]


In [18]:
encoder = preprocessing.OneHotEncoder()
encoder.fit([[2,3,5,3], [1,3,5,3], [2,3,2,12],[1,2,4,3]])
encoded_vector = encoder.transform([[2,3,5,3]]).toarray()
print('\nEncoded Vector = ', encoded_vector)


Encoded Vector =  [[0. 1. 0. 1. 0. 0. 1. 1. 0.]]
